### ISSUE TITLE
运行环境报错

### ISSUE THREAD

**Issue by dbbice** [renli1024/SE-GNN#4]
您好！我在运行的过程中遇到问题，报错如下：
------Config------
 {'dataset': 'FB15k_237', 'epoch': 600, 'batch_size': 1024, 'learning_rate': 0.00035, 'h_dim': 450, 'pred_rel_w': False, 'label_smooth': 0.1, 'kg_layer': 2, 'rm_rate': 0.5, 'ent_drop': 0.3, 'rel_drop': 0.1, 'comp_op': 'mul', 'bn': False, 'k_h': 15, 'k_w': 30, 'conv_drop': 0.3, 'ent_drop_pred': 0.3, 'fc_drop': 0.5, 'ker_sz': 8, 'out_channel': 200, 'device': 0, 'max_no_improve': 50, 'cpu_worker_num': 10, 'warmup_epoch': 5}
[2023-02-28 11:28:06,052][root][INFO] - Code dir path: code
[2023-02-28 11:28:06,052][root][INFO] - Config dir path: config
[2023-02-28 11:28:06,052][root][INFO] - Model save path: /home/yuxc/SE-GNN-main/data/output/FB15k_237/2023-02-28/11-28-05
cp: cannot stat 'code': No such file or directory
cp: cannot stat 'config': No such file or directory
/home/yuxc/anaconda3/envs/hypernode/lib/python3.6/site-packages/torch/nn/modules/container.py:434: UserWarning: Setting attributes on ParameterList is not supported.
  warnings.warn("Setting attributes on ParameterList is not supported.")
[2023-02-28 11:28:13,029][root][INFO] - kg # node: 14505
[2023-02-28 11:28:13,030][root][INFO] - kg # edge: 544230
[2023-02-28 11:28:13,030][root][INFO] - kg # zero deg node: 0
[2023-02-28 11:28:13,030][root][INFO] - ---Load Train Data---
[2023-02-28 11:28:15,710][root][INFO] - -----Model Parameter Configuration-----
[2023-02-28 11:28:15,710][root][INFO] - Parameter ent_emb: torch.Size([14541, 450]), require_grad = True
[2023-02-28 11:28:15,710][root][INFO] - Parameter pred_rel_emb: torch.Size([474, 450]), require_grad = True
[2023-02-28 11:28:15,710][root][INFO] - Parameter edge_layers.0.neigh_w: torch.Size([450, 450]), require_grad = True
[2023-02-28 11:28:15,710][root][INFO] - Parameter edge_layers.1.neigh_w: torch.Size([450, 450]), require_grad = True
[2023-02-28 11:28:15,710][root][INFO] - Parameter node_layers.0.neigh_w: torch.Size([450, 450]), require_grad = True
[2023-02-28 11:28:15,710][root][INFO] - Parameter node_layers.1.neigh_w: torch.Size([450, 450]), require_grad = True
[2023-02-28 11:28:15,710][root][INFO] - Parameter comp_layers.0.neigh_w: torch.Size([450, 450]), require_grad = True
[2023-02-28 11:28:15,710][root][INFO] - Parameter comp_layers.1.neigh_w: torch.Size([450, 450]), require_grad = True
[2023-02-28 11:28:15,710][root][INFO] - Parameter rel_embs.0: torch.Size([474, 450]), require_grad = True
[2023-02-28 11:28:15,710][root][INFO] - Parameter rel_embs.1: torch.Size([474, 450]), require_grad = True
[2023-02-28 11:28:15,711][root][INFO] - Parameter predictor.bn0.weight: torch.Size([1]), require_grad = True
[2023-02-28 11:28:15,711][root][INFO] - Parameter predictor.bn0.bias: torch.Size([1]), require_grad = True
[2023-02-28 11:28:15,711][root][INFO] - Parameter predictor.bn1.weight: torch.Size([200]), require_grad = True
[2023-02-28 11:28:15,711][root][INFO] - Parameter predictor.bn1.bias: torch.Size([200]), require_grad = True
[2023-02-28 11:28:15,711][root][INFO] - Parameter predictor.bn2.weight: torch.Size([450]), require_grad = True
[2023-02-28 11:28:15,711][root][INFO] - Parameter predictor.bn2.bias: torch.Size([450]), require_grad = True
[2023-02-28 11:28:15,711][root][INFO] - Parameter predictor.conv.weight: torch.Size([200, 1, 8, 8]), require_grad = True
[2023-02-28 11:28:15,711][root][INFO] - Parameter predictor.fc.weight: torch.Size([450, 105800]), require_grad = True
[2023-02-28 11:28:15,712][root][INFO] - Training... total epoch: 600, step: 88200
Error executing job with overrides: []
Traceback (most recent call last):
  File "code/run.py", line 146, in main
    train_log = train_step(model, batch_data, kg, optimizer, scheduler)
  File "/home/yuxc/SE-GNN-main/code/model_helper.py", line 27, in train_step
    kg.remove_edges(rm_edges)
AttributeError: 'DGLHeteroGraph' object has no attribute 'remove_edges'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

第一处为project_dir_path路径获取问题，第二处是dgl环境问题，请问您知道如何解决吗

**Comment by renli1024** [comment]
请问dgl的版本是多少? 在 0.7.2 version下应该是可以运行的, 你可以试试.

**Comment by dbbice** [comment]
> 请问dgl的版本是多少? 在 0.7.2 version下应该是可以运行的, 你可以试试.

您好，我重装了0.6.1的dgl可以运行的。这个改变device可以多gpu运行吗？

**Comment by renli1024** [comment]
应该不可以, 代码是在单gpu上实现的, device主要用于切换gpu的.

**Comment by dbbice** [comment]
> 应该不可以, 代码是在单gpu上实现的, device主要用于切换gpu的.
感谢您的回复~那SE-GNN在FB15K这种大一点的数据集上的效果你们尝试过吗？有没有相关的参数可以参考，还是SE-GNN更适合小数据集~

**Comment by renli1024** [comment]
我们没有在FB15K上的具体参数, 不过一般来说对结果影响较大的有隐层维度`h_dim`和dropout比率, 你可以尝试调整下.

**Comment by dbbice** [comment]
> 我们没有在FB15K上的具体参数, 不过一般来说对结果影响较大的有隐层维度`h_dim`和dropout比率, 你可以尝试调整下.

好的 感谢您的回复~~
